### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by tin2tin** [joshuaKnauber/bpy-chat-gpt#2]
Great script. I was very curious how chatGPT would be able to work with my Blender screenwriter add-on, so I did a fork of your add-on to try it out for this purpose: https://github.com/tin2tin/bpy-chat-gpt/tree/chatGPT_Screenwriter
I hope that is okay with you? 

It seems to work very well. However, I had to give them my billing info for it to work.  

Some video:

https://user-images.githubusercontent.com/1322593/224118304-91d47502-96f4-402f-9cfb-4d6e0acf6a76.mp4

And a tweet:
https://twitter.com/tintwotin/status/1633828053737672704

**Comment by joshuaKnauber** [comment]
Yeah sure, go ahead
