### ISSUE TITLE
Problem connecting to internet

### ISSUE THREAD

**Issue by ACMOIDRE** [joshuaKnauber/bpy-chat-gpt#3]
HTTP Error 429: Too Many Requests

**Comment by joshuaKnauber** [comment]
Are you still getting that? Might just be chat gpt being overwhelmed

**Comment by tin2tin** [comment]
I got that error too for a full day, until I gave openai my billing info, and set a very low hard limit.

**Comment by ACMOIDRE** [comment]
hey,
how can i set limit

**Comment by joshuaKnauber** [comment]
@ACMOIDRE Go to your open ai account to billing

**Comment by ACMOIDRE** [comment]
yeah, i followed you tuts still struggling man.
can make small tuts of 1 minute or snapphoto blurr personal details.
thanks for response.
really appreciated.
